<?php

/**
 *  Implements hook_menu().
 */
function loom_quickbackup_menu() {
  $items['quickbackup'] = array(
    'title' => 'Quickbackup',
    'access callback' => 'loom_quickbackup_access',
    'page callback' => 'loom_quickbackup_backup'
  );

  return $items;
}

function loom_quickbackup_access() {
  if (!isset($GLOBALS['conf']['quickbackup_key'])) {
    return FALSE;
  }

  $key = $GLOBALS['conf']['quickbackup_key'];

  if(strlen(trim($key)) == 0) {
    return FALSE;
  }

  if (!isset($_GET['key']) || (isset($_GET['key']) && $_GET['key'] != $key)) {
    return FALSE;
  }

  return TRUE;
}

function loom_quickbackup_backup() {
  backup_migrate_include('profiles', 'destinations');

  $profile = 'default';

  if (isset($GLOBALS['conf']['quickbackup_profile']) && intval($GLOBALS['conf']['quickbackup_profile']) > 0) {
    $profile = intval($GLOBALS['conf']['quickbackup_profile']);
  }

  $settings = _backup_migrate_profile_saved_default_profile($profile);
  $settings->destination_id = array('download');

  backup_migrate_perform_backup($settings);
}
